/*
 * Ground Truth · Table Talk — question deck
 * Top 100 questions curated from the Luma RSVP submissions (cleaned, unattributed).
 * Source: "Ground Truth - RSVP Panel Questions_1.xlsx", tab "Top 100 Questions", 2026-09-16.
 * Order is reshuffled on every page load (see app.js). To update: replace the strings below.
 */

const PLACEHOLDER = false;

const QUESTIONS = [
  "How do you decide which decisions an agent makes on its own and which must go to a human?",
  "What makes an action safe to automate: the measured error rate, the cost of the worst single failure, or whether it can be reversed?",
  "Where have you drawn the line between the model deciding and a human signing off, and what failure moved it there?",
  "Which agent actions should never be delegated, however good the model gets?",
  "How do you set that boundary deliberately, rather than discovering it after the first bad outcome?",
  "What changes about the design when an agent moves from recommending an action to executing it?",
  "Should the automation boundary be drawn by risk tier rather than by task type?",
  "Is human-in-the-loop the right default, or should a human only be added where there is a clear benefit?",
  "How do you tell a genuine control from a review step that exists only to satisfy an auditor?",
  "What signal actually triggers a handoff to a human in your system?",
  "Is model confidence a usable routing signal, or do you escalate on input characteristics and independent checks instead?",
  "How did you arrive at your escalation threshold, and how has it moved since your first bad outcome?",
  "Should escalation be driven by model confidence or by the real-world risk of the decision?",
  "How do you flag an output for human review without breaking low-latency requirements?",
  "How do you test that an agent reliably escalates a hard case, rather than just claiming it did?",
  "When should an agent stop entirely instead of escalating?",
  "Once a model is right 95% of the time, how do you stop reviewers approving by default?",
  "What do you instrument to detect that human review has decayed into a rubber stamp, before an auditor does?",
  "How do you measure whether a review step is still catching real errors?",
  "How do you keep a reviewer genuinely adversarial six months into a deployment?",
  "Most systems record whether the human approved. Has anyone instrumented what the human changed?",
  "Is approval fatigue an argument for removing capability structurally rather than adding another gate?",
  "Who owns the mistake when a time-pressed reviewer approves an output they could not fully check?",
  "Should an agent be allowed to hold a professional licence and take official actions?",
  "Is your automation boundary set by technical limits, or by liability and insurability?",
  "How does human-in-the-loop design change when the reviewer carries personal legal liability?",
  "How do you keep review meaningful when the reviewer is accountable but lacks the context to overrule the model?",
  "How do you build evals you actually trust when there is no ground truth to check against?",
  "Is LLM-as-judge good enough, or are most teams fooling themselves with it?",
  "How do you establish that your evaluator is itself trustworthy?",
  "How do you design evals for multi-step agentic systems, where the space of possible behaviour explodes?",
  "How do you evaluate quality when the right answer is subjective or has many valid forms?",
  "At what reliability level does human review create leverage rather than simply move the work to verification?",
  "How do you add human checkpoints without destroying the latency and scale benefits of automation?",
  "Human review is expensive. How do you decide it is still worth paying for?",
  "How do you handle escalations that arrive outside working hours?",
  "How do you manage reviewer cognitive load when agents generate far more work to check than before?",
  "What do you persist so that a past decision can be replayed and defended months later?",
  "How do you make an agent's reasoning legible enough to defend to a regulator after the fact?",
  "Regulators want every individual decision explained, not aggregate accuracy. How do you design review for that?",
  "Should the system that plans an action ever be the system allowed to execute it?",
  "Where should the enforcement layer sit when model behaviour can never be fully guaranteed?",
  "What does governance look like when the risk is the workflow itself, not just the output?",
  "How do you catch the errors a system does not know it is making?",
  "How do you detect a silent regression, where the answer still looks right but the reasoning path changed?",
  "Correctness is measurable, completeness is not. How do you know what the model quietly left out?",
  "Which metrics have proved most predictive of safe production behaviour when failures are rare but costly?",
  "Do you measure model accuracy, or the accuracy of the combined human-plus-AI system in production?",
  "How do you validate reliability when a model performs well on average but fails catastrophically at the edges?",
  "In physical AI, where does human review add the most value: at the data layer or at deployment?",
  "Will human-in-the-loop still be necessary in ten years, or is it an artefact of today's models?",
  "Is human-in-the-loop a safety control, or an architectural bug you should engineer away?",
  "How do you design for an agent that exceeds its authority or is deliberately manipulated?",
  "How do you prove ROI when humans are still in the process and no hard costs have come out?",
  "Where should scarce domain experts sit in an agentic workflow to create the most leverage?",
  "When models, prompts, tools and regulations all change independently, where should the reliability guarantee live?",
  "Is the future deterministic guardrails, or agents supervising other agents?",
  "Is compliance a real moat, or a head start you are calling a moat?",
  "What part of your compliance posture is genuinely hard for a well-funded competitor to copy?",
  "What is your falsifiable test for telling durable domain depth from a temporary advantage?",
  "Once incumbents catch up on certifications, what keeps compliance durable rather than table stakes?",
  "Which parts of compliance do you expect to still be expensive in five years?",
  "A moat has to be hard to copy, not just expensive. Which parts of yours actually qualify?",
  "If almost nobody audits what was filed, is compliance a moat or a ritual?",
  "If AI makes compliance work dramatically cheaper, does the moat invert and favour challengers?",
  "Is the real moat trust and reputation, with compliance just the entry ticket?",
  "How do you know you have built a moat rather than an expensive bureaucracy?",
  "If a frontier model closes the domain-knowledge gap in eighteen months, what is left that is defensible?",
  "Is the defensibility in understanding the domain, or in the infrastructure that makes that understanding reliable enough to act on?",
  "Models are excellent at knowledge recall. Why would encoded domain knowledge hold as a moat?",
  "Which domain-specific component you built did a newer model make obsolete, and which became more valuable?",
  "If every jurisdiction published perfect machine-readable rules tomorrow, what would remain of the moat?",
  "Capability and verifiability are different things. Is the durable moat domain depth, or whatever proves an output is right?",
  "At what stage should an early-stage AI startup invest seriously in compliance?",
  "Which compliance investments help win customers early, and which are premature overhead?",
  "What should be built into the product, data model and audit trail from day one?",
  "What is genuinely table stakes at pre-seed, and what burns runway you needed elsewhere?",
  "What stops a regulated incumbent from building this in-house once the models are good enough?",
  "Does compliance favour incumbents, or smaller teams who can automate it faster than a large company can move?",
  "How does a startup break into a market where legacy vendors already hold compliance as their moat?",
  "Vanta and Drata turned SOC 2 into a commodity. Where is the line between compliance you buy and compliance that is structural?",
  "A moat only holds if enforcement arrives. How do you underwrite one whose value depends on something you do not control?",
  "How do you handle contradictory requirements across jurisdictions, where one demands retention and another deletion?",
  "How are teams translating changing regulation into auditable, maintainable controls without stalling the product?",
  "Does regulation that never stops changing strengthen the moat, or just raise the maintenance cost forever?",
  "Which compliance artifact moves procurement first: SOC 2, audit logs, or something else?",
  "Can you name a deal you won specifically on a compliance artifact rather than on price or product?",
  "How do you sell compliance as a competitive advantage rather than a cost?",
  "Is there a real opportunity in compliance-as-code, in the way there was for infrastructure-as-code?",
  "What happens to the moat if formal verification of compliance becomes routine in agent development?",
  "Is the moat the determinations themselves, or the accountability you are willing to carry when one is wrong?",
  "Are customers buying compliance, or buying someone else to blame when it goes wrong, and how do you price that?",
  "Where does the durable moat actually sit: proprietary data, workflow integration, evaluation infrastructure, or the execution layer?",
  "Which of those advantages compounds fastest with usage?",
  "Is the real asset the record of determinations that were challenged by an auditor and survived?",
  "How many years of that record does a competitor need before they genuinely cannot catch up?",
  "What makes an engineering culture treat compliance as a product requirement rather than a legal checkbox?",
  "Which industries have the deepest compliance wall and the most to gain from AI?",
  "How do you build compliance in without slowing iteration so much that larger competitors reach the market first?",
  "What is the compliance requirement that is hardest to actually prove to a regulator or an enterprise buyer?",
];
